---
title: "Staff, Students and Affiliates"
output:
    distill::distill_article:
        toc: true
---

<style>
.flex-grid-thirds {
    display: flex;
    flex-flow: row wrap;
    align-content: center;
}

.flex-grid-thirds .col {
    width: 33%;
    margin-top: 0px;
    margin-bottom: 0px;
}

@media (max-width: 400px) {
    .flex-grid-thirds {
        display: block;
        .col {
            width: 100%;
            margin = 0 0 10px 0;
        }
    }
}

* {
    box-sizing: border-box;
}
.col {
    padding: 10px;
}

h2 {
    text-align: center;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Chief Investigators
```{r, results='asis', layout = "l-body-outset"}
cat(":::: flex-grid-thirds \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "ci") {
          condensr::generate_markdown_for_member(staff_member)
      }
}
cat("::::")
```

## Post-doctoral Researchers

## Students

## Affiliated Researchers
```{r, results='asis', layout = "l-body-outset"}
cat(":::: flex-grid-thirds \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "affiliate") {
          condensr::generate_markdown_for_member(staff_member)
      }
}
cat("::::")
```