project:
  type: website
  output-dir: ../_site/spark

website:
  title: "Strengthening preparedness in the Asia-Pacific region through knowledge"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "People"
        href: people.html
      - text: "Publications"
        href: publications.html
      - text: "Other Consortia"
        menu:
          - text: "SPECTRUM"
            href: ../spectrum/index.html
          - text: "PRISM<sup>2</sup>"
            href: https://www.prism.edu.au
    foreground: "#9f1f63"
    background: "#FFFFFF"
    logo: images/logo_spark.png
  favicon: images/favicon.png
        
        

format:
  html:
    theme: cosmo
    css: [style_spark.css, custom_scss.scss]
    toc: true