project:
  type: website
  output-dir: ../_site/spark

website:
  title: "SPARK"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "People"
        href: people.html
      - text: "Other Consortia"
        menu:
          - text: "SPECTRUM"
            href: ../spectrum/index.html
          - text: "PRISM<sup>2</sup>"
            href: https://www.prism.edu.au
    background: "#F05662"
    logo: ../images/logo_spark.png
  favicon: images/favicon.png
        
        

format:
  html:
    theme: cosmo
    css: [theme.css, custom_scss.scss]
    toc: true