---
title: "People"
---

```{css, echo=FALSE}
/* .flex-grid-thirds {
    display: flex;
    flex-flow: row wrap;
    align-content: center;
}

.flex-grid-thirds .col {
    width: 33%;
    margin-top: 0px;
    margin-bottom: 2px;
    margin-right: 2px
}

@media (max-width: 400px) {
    .flex-grid-thirds {
        display: block;
        .col {
            width: 100%;
            margin = 0 0 10px 0;
        }
    }
}

* {
    box-sizing: border-box;
} */
/* .col {
    padding: 10px;
    border-style: solid;
    border-spacing: 20px;
    border-color: #cbd1cc;
    border-width: thin;
    transition: background-color .5s;
} */

.boxes {
    justify-content: left;
}

.col {
    display: block;
}

.col:hover {
    background-color: #dcdcdc;
}

h3 {
    text-align: center;
}
```

```{r setup, include=FALSE}
#| echo: false
#| warning: false
#| message: false
knitr::opts_chunk$set(echo = FALSE)
source("load_data.R")
```

## Chief Investigators
```{r, results='asis'}
cat(":::: boxes \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "ci") {
        condensr::generate_markdown_for_member(staff_member)
    }
}
cat("::::")
```

## Post-doctoral Researchers

## Students

## Affiliated Researchers
```{r, results='asis'}
cat(":::: boxes \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "affiliate") {
        condensr::generate_markdown_for_member(staff_member)
    }
}
cat("::::")
```