project:
  type: website
  output-dir: ../_site/spectrum
  pre-render: cp -R ../spark/news news

website:
  title: "Supporting Participatory Evidence generation to Control Transmissible diseases in our Region Using Modelling"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "People"
        href: people.html
      - text: "Partners"
        href: key_collaborators.html
      - text: "Publications"
        href: publications.html
      - text: "News and Events"
        href: news.html
      - text: "Other Consortia"
        menu:
          - text: "SPARK"
            href: ../spark/index.html
          - text: "PRISM<sup>2</sup>"
            href: https://www.prism.edu.au
    foreground: "#F05662"
    background: "#FFFFFF"
    logo: ../images/logo_spectrum.png
  favicon: images/favicon.png
  body-footer: |
    For more information or to report issues, please contact <mailto:spectrum-spark@unimelb.edu.au>

format:
  html:
    theme: cosmo
    css: [style_spectrum.css, custom_scss.scss]
    toc: true