project:
  type: website
  output-dir: ../_site/spectrum
  pre-render: 
    - cp -a ../news/. ./news/
    - quarto run ../update_data.R

website:
  title: |
    Supporting Participatory Evidence generation to Control
    Transmissible diseases in our Region Using Modelling
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "People"
        href: people.html
      - text: "Partners"
        href: key_collaborators.html
      - text: "Resources"
        menu:
          - text: "Publications"
            href: "publications.html#publications"
          - text: "Video & Media"
            href: "publications.html#video"
          - text: "Articles"
            href: "publications.html#articles"
          - text: "Projects"
            href: projects.html
      - text: "News and Events"
        href: news.html
      - text: "Other Consortia"
        menu:
          - text: "Home"
            href: ../index.html
          - text: "SPARK"
            href: ../spark/index.html
          - text: "PRISM<sup>2</sup>"
            href: https://www.prism.edu.au
    foreground: "#F05662"
    background: "#FFFFFF"
    logo: ../images/logo_spectrum.png
  favicon: images/favicon.png
  page-footer:
    left: |
      For more information or to report issues, please contact <a href='mailto:spectrum-spark@unimelb.edu.au'>the consortia project inbox</a>.
    right: |
      SPECTRUM is funded by the National Health and Medical Research Council (NHMRC).
    background: "#F05662"
    foreground: "#FFFFFF"

format:
  html:
    theme: cosmo
    css: [style_spectrum.css, custom_scss.scss]
    toc: true