---
title: "Publications"
format:
    html:
        page-layout: full
---

```{css, echo=FALSE}
.vert-align {
    margin: auto;
}

.margin-sidebar {
    display: none;
}

```

```{r setup, include=FALSE}
#| echo: false
#| warning: false
#| message: false
knitr::opts_chunk$set(echo = FALSE)
source("load_data.R")
library(tools)
library(DT)
```

This page shows all the publications produced as part of these consortia. The list is searchable, and you can click the globe on any row to be taken to the journal webpage for the full paper.

```{r list-publications}
#| results: 'asis'
#| echo: false

svg_string <- '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link" viewBox="0 0 16 16">
  <path d="M6.354 5.5H4a3 3 0 0 0 0 6h3a3 3 0 0 0 2.83-4H9c-.086 0-.17.01-.25.031A2 2 0 0 1 7 10.5H4a2 2 0 1 1 0-4h1.535c.218-.376.495-.714.82-1z"/>
  <path d="M9 5.5a3 3 0 0 0-2.83 4h1.098A2 2 0 0 1 9 6.5h3a2 2 0 1 1 0 4h-1.535a4.02 4.02 0 0 1-.82 1H12a3 3 0 1 0 0-6H9z"/>
</svg>'

publications_table <- lapply(publication_list, function(pub) {
    data.frame(
        Date = pub$date,
        Link = glue::glue("<a href={pub$link} target='_blank'>{svg_string}</a>"),
        Citation = markdown::mark_html(
            text = pub$citation,
            template = FALSE
        ) |>
            stringr::str_replace("(\r\n|\n).*", "") |>
            stringr::str_replace_all("<p>|</p>", "")
    )
}) |> bind_rows()

DT::datatable(
    publications_table,
    rownames = FALSE,
    escape = FALSE,
    colnames = c("Date", "Link", "Citation"),
    options = list(
        columnDefs = list(
            list(width = "100px", targets = 0),
            list(className = "dt-center", targets = c(0, 1)),
            list(className = "vert-align", targets = 2)
        )
    )
)
```